### ISSUE TITLE
Balance N/A when opening extension - requires switching between accounts to fix

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#60]
Getting consistent N/A balances when opening extension. Requires me to switch between accounts a few times before it queries.

![Screen Shot 2019-05-06 at 10 19 23 pm](https://user-images.githubusercontent.com/39804936/57224502-02022b00-704d-11e9-85f6-b9d2727b6618.png)

**Comment by fyang1024** [comment]
This is probably because of slow network. The balance component originally waits up to 5 seconds to get balance. Now it's changed to 10 seconds to cater for sometimes slow internet. We now use Polkadot public test rpc endpoint. It may be slow or even down from time to time. Later on if Polkadot ecosystem has something like infura for Ethereum, we'll have highly available rpc endpoints. Or we can deploy our nodes in different area
